baseurl = "http://rpi.science.uoit.ca/"
languageCode = "en-us"
title = "RPi Labs"
pygmentsstyle = "tango"

[params]
Description = "Laboratories on Raspberry Pi for UOIT students"
Copyright = " "
Logo = "/images/logo.png"

