baseurl = "https://rpi.science.ontariotechu.ca/"
languageCode = "en-CA"
title = "RPi Labs"
theme = "hyde-hyde"
enableGitInfo = true

[params]
Description = "Laboratories on Raspberry Pi for CSCI 2050U"
#Copyright = " "
Logo = "/images/logo.png"
authorimage = "/images/logo.png"
highlightjs = true
highlightjslanguages = ["python", "armasm"]
highlightjsstyle = "monokai"

[params.social]
github = "uoitsci/pi-labs"

[[menu.main]]
name = "Home"
url = "/"

[[menu.main]]
name = "Labs"
url = "/lab/"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
definitionList = true
table = true

#[imaging]
#resampleFilter = "linear" #"lanczos"
